version: '3.9'
services:

  php:
    # image: creased/php:7-fpm-alpine-mysqli
    build: .
    container_name: lemp_php
    restart: always
    volumes:
      - ./src/:/var/www/html
    expose:
      - "9000"
  nginx:
    image: nginx:stable-alpine
    container_name: lemp_nginx
    restart: always
    volumes:
      - ./src/:/var/www/html
      - ./nginx-config/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx-config/conf.d:/etc/nginx/conf.d:ro
    volumes_from:
      - php
    ports:
      - 8085:80

  db:
    image: mysql
    container_name: lemp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports: 
      - "6033:3306"
    volumes: 
      - ./mysql/initdb/:/docker-entrypoint-initdb.d
      - ./mysql/data/:/var/lib/mysql
      # - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links: 
      - db
    restart: always
    ports: 
      - 8086:80